require('dotenv').config();
const mongoose = require('mongoose');
const Gem      = require('./models/Gem');
const Admin    = require('./models/Admin');

const GEMS = [
  {id:"ruby",name:"Ruby",hindi:"Manik (माणिक)",scientific:"Corundum — Al₂O₃",category:"red",badge:"precious",vedic:true,planet:"☀️",hardness:9.0,priceMin:73626,priceMax:3241758,priceDisplay:"₹73,626 – ₹32,41,758",unit:"per carat (Burma unheated)",desc:"The Emperor of Precious Gems. Ruby — known as Manik in Vedic astrology — is ruled by the Sun and bestows authority, confidence, and vitality. Untreated Burmese pigeon-blood rubies are among the most valuable stones on earth.",specs:{Origin:"Burma, Mozambique, Sri Lanka",Hardness:"9.0 Mohs",Clarity:"Inclusions accepted",Treatment:"Heat common; unheated premium","Carat Rate":"₹73,626 – ₹32,41,758/ct"},benefits:["Boosts confidence","Sun planet stone","Career success","Vitality & health"],images:[]},
  {id:"garnet",name:"Red Garnet",hindi:"Tamra Mani",scientific:"Pyrope/Almandine Garnet",category:"red",badge:"semi",vedic:false,planet:"♂️",hardness:7.5,priceMin:1868,priceMax:46154,priceDisplay:"₹1,868 – ₹46,154",unit:"per carat",desc:"Deep crimson, affordable luxury. Red garnets range from soft rose to intense bordeaux. The ideal everyday gemstone — durable, brilliant, and available in large sizes.",specs:{Origin:"India, Africa, Brazil",Hardness:"7.5 Mohs",Clarity:"Eye-clean typical",Treatment:"None typical","Carat Rate":"₹1,868 – ₹46,154/ct"},benefits:["Energy & stamina","Affordable luxury","Emotional balance"],images:[]},
  {id:"redcoral",name:"Red Coral",hindi:"Moonga (मूंगा)",scientific:"Corallium rubrum — Organic",category:"red",badge:"precious",vedic:true,planet:"♂️",hardness:3.5,priceMin:2747,priceMax:27473,priceDisplay:"₹2,747 – ₹27,473",unit:"per carat (Italian ox-blood)",desc:"Ruled by Mars (Mangal), Red Coral is one of the Navaratna. Ox-blood red Italian coral commands the highest value. Essential for Manglik individuals seeking courage.",specs:{Origin:"Mediterranean, Japan, India",Hardness:"3.5 Mohs",Clarity:"Opaque",Treatment:"Wax polish","Carat Rate":"₹2,747 – ₹27,473/ct"},benefits:["Mars planet stone","Removes Mangal Dosha","Energy & courage","Blood health"],images:[]},
  {id:"spinel",name:"Red Spinel",hindi:"Sphatik Lal",scientific:"Spinel — MgAl₂O₄",category:"red",badge:"semi",vedic:false,planet:"☀️",hardness:8.0,priceMin:5495,priceMax:923077,priceDisplay:"₹5,495 – ₹9,23,077",unit:"per carat (Mahenge)",desc:"Historically confused with ruby. Spinel is now prized in its own right. Vivid reds from Mahenge, Tanzania are usually unheated and fetch extraordinary premiums.",specs:{Origin:"Burma, Tanzania, Sri Lanka",Hardness:"8.0 Mohs",Clarity:"Eye-clean",Treatment:"None typical","Carat Rate":"₹5,495 – ₹9,23,077/ct"},benefits:["Rare collector gem","Unheated natural","High brilliance","Investment stone"],images:[]},
  {id:"bluesapphire",name:"Blue Sapphire",hindi:"Neelam (नीलम)",scientific:"Corundum — Al₂O₃",category:"blue",badge:"precious",vedic:true,planet:"♄",hardness:9.0,priceMin:46154,priceMax:4615385,priceDisplay:"₹46,154 – ₹46,15,385",unit:"per carat (Kashmir unheated)",desc:"The most powerful planetary gem in Vedic astrology. Neelam represents Saturn and can transform luck, career, and wealth instantly.",specs:{Origin:"Kashmir (rarest), Ceylon, Burma",Hardness:"9.0 Mohs",Clarity:"Eye-clean ideal",Treatment:"Heat common; unheated premium","Carat Rate":"₹46,154 – ₹46,15,385/ct"},benefits:["Saturn planet stone","Career & wealth","Rapid manifestation","Justice & discipline"],images:[]},
  {id:"tanzanite",name:"Tanzanite",hindi:"Tanzanite",scientific:"Zoisite — Calcium Aluminium Silicate",category:"blue",badge:"precious",vedic:false,planet:"♀️",hardness:6.5,priceMin:9231,priceMax:138462,priceDisplay:"₹9,231 – ₹1,38,462",unit:"per carat",desc:"Found only near Mt. Kilimanjaro, Tanzania. Tanzanite's mesmerizing blue-violet changes colour under different lighting. 1000x rarer than diamond.",specs:{Origin:"Tanzania ONLY — Merelani Mines",Hardness:"6.5 Mohs",Clarity:"Eye-clean",Treatment:"Heat standard","Carat Rate":"₹9,231 – ₹1,38,462/ct"},benefits:["Investment gem","Extremely rare","Transformative energy","Collector's gem"],images:[]},
  {id:"aquamarine",name:"Aquamarine",hindi:"Beruj (बेरूज)",scientific:"Beryl — Be₃Al₂Si₆O₁₈",category:"blue",badge:"semi",vedic:true,planet:"♀️",hardness:7.5,priceMin:2308,priceMax:184615,priceDisplay:"₹2,308 – ₹1,84,615",unit:"per carat (Santa Maria)",desc:"Named after the sea. Aquamarine's serene, crystal-clear blue is perfect for clarity, peace, and communication.",specs:{Origin:"Brazil, Pakistan, Nigeria",Hardness:"7.5 Mohs",Clarity:"Eye-clean typical",Treatment:"Heat occasional","Carat Rate":"₹2,308 – ₹1,84,615/ct"},benefits:["Peace & clarity","Communication","Venus energy","Throat chakra"],images:[]},
  {id:"bluetopaz",name:"Blue Topaz",hindi:"Tapaz",scientific:"Topaz — Al₂SiO₄(F,OH)₂",category:"blue",badge:"semi",vedic:false,planet:"♃",hardness:8.0,priceMin:462,priceMax:13846,priceDisplay:"₹462 – ₹13,846",unit:"per carat",desc:"Sky to London Blue topaz offer brilliant colour at truly accessible prices. At 8 Mohs hardness, topaz rivals sapphire in durability.",specs:{Origin:"Brazil, Pakistan, Sri Lanka",Hardness:"8 Mohs",Clarity:"Eye-clean typical",Treatment:"Irradiation (standard)","Carat Rate":"₹462 – ₹13,846/ct"},benefits:["Affordable brilliance","Focus & clarity","Throat chakra","Jupiter energy"],images:[]},
  {id:"lapislazuli",name:"Lapis Lazuli",hindi:"Lajward (लाजवर्द)",scientific:"Lazurite + Calcite + Pyrite",category:"blue",badge:"semi",vedic:true,planet:"♄",hardness:5.5,priceMin:923,priceMax:13846,priceDisplay:"₹923 – ₹13,846",unit:"per carat (Afghan AAA)",desc:"The stone of pharaohs. Afghan lapis is the world gold standard — deep royal blue with golden pyrite flecks, treasured for 6,000 years.",specs:{Origin:"Afghanistan (finest), Chile, Russia",Hardness:"5.5 Mohs",Clarity:"Opaque",Treatment:"Wax/oil typical","Carat Rate":"₹923 – ₹13,846/ct"},benefits:["Spiritual wisdom","Saturn energy","Third eye chakra","Ancient healing"],images:[]},
  {id:"emerald",name:"Emerald",hindi:"Panna (पन्ना)",scientific:"Beryl — Be₃Al₂Si₆O₁₈",category:"green",badge:"precious",vedic:true,planet:"☿",hardness:7.5,priceMin:27692,priceMax:2769231,priceDisplay:"₹27,692 – ₹27,69,231",unit:"per carat (Colombian no-oil)",desc:"Ruled by Mercury, Emerald governs intellect, communication, and business. Colombian emeralds are the world standard.",specs:{Origin:"Colombia, Zambia, Brazil",Hardness:"7.5 Mohs",Clarity:"Jardins accepted",Treatment:"Oil/resin very common","Carat Rate":"₹27,692 – ₹27,69,231/ct"},benefits:["Mercury planet stone","Intellect & memory","Business success","Communication"],images:[]},
  {id:"tsavorite",name:"Tsavorite Garnet",hindi:"Harit Mani",scientific:"Grossular Garnet",category:"green",badge:"semi",vedic:false,planet:"♃",hardness:7.5,priceMin:13846,priceMax:739560,priceDisplay:"₹13,846 – ₹7,39,560",unit:"per carat",desc:"A vivid green garnet from East Africa that rivals emerald in brilliance and clarity. Always untreated. Rare above 2 carats.",specs:{Origin:"Kenya, Tanzania",Hardness:"7.5 Mohs",Clarity:"Eye-clean typical",Treatment:"None — always untreated","Carat Rate":"₹13,846 – ₹7,39,560/ct"},benefits:["Rarer than emerald","Untreated natural","Jupiter energy","Heart chakra"],images:[]},
  {id:"peridot",name:"Peridot",hindi:"Zabarjad",scientific:"Forsterite — (Mg,Fe)₂SiO₄",category:"green",badge:"semi",vedic:false,planet:"☿",hardness:6.5,priceMin:923,priceMax:46154,priceDisplay:"₹923 – ₹46,154",unit:"per carat (Pakistan fine)",desc:"The only gem that forms in the Earth's mantle. Peridot's olive-lime green is completely natural — never treated.",specs:{Origin:"Pakistan (Kohistan), Arizona, Egypt",Hardness:"6.5 Mohs",Clarity:"Eye-clean typical",Treatment:"None — never treated","Carat Rate":"₹923 – ₹46,154/ct"},benefits:["100% untreated","Healing energy","Stress relief","Mercury energy"],images:[]},
  {id:"yellowsapphire",name:"Yellow Sapphire",hindi:"Pukhraj (पुखराज)",scientific:"Corundum — Al₂O₃",category:"yellow",badge:"precious",vedic:true,planet:"♃",hardness:9.0,priceMin:18462,priceMax:554945,priceDisplay:"₹18,462 – ₹5,54,945",unit:"per carat (Ceylon unheated)",desc:"The most beloved Vedic gemstone in India. Pukhraj represents Jupiter — planet of wealth, wisdom, and blessings.",specs:{Origin:"Sri Lanka, Thailand, Madagascar",Hardness:"9.0 Mohs",Clarity:"Eye-clean preferred",Treatment:"Heat occasional; unheated prized","Carat Rate":"₹18,462 – ₹5,54,945/ct"},benefits:["Jupiter planet stone","Wealth & prosperity","Marriage & children","Wisdom"],images:[]},
  {id:"citrine",name:"Citrine",hindi:"Sunela (सुनेला)",scientific:"Quartz — SiO₂",category:"yellow",badge:"semi",vedic:true,planet:"♃",hardness:7.0,priceMin:462,priceMax:9231,priceDisplay:"₹462 – ₹9,231",unit:"per carat",desc:"The merchant's stone. Citrine ranges from pale lemon to deep cognac-orange. Affordable, durable, ideal for daily wear.",specs:{Origin:"Brazil, Bolivia, Spain",Hardness:"7 Mohs",Clarity:"Eye-clean typical",Treatment:"Heat from amethyst","Carat Rate":"₹462 – ₹9,231/ct"},benefits:["Wealth manifestation","Jupiter substitute","Positive energy","Affordable"],images:[]},
  {id:"hessonite",name:"Hessonite Garnet",hindi:"Gomed (गोमेद)",scientific:"Grossular Garnet",category:"yellow",badge:"precious",vedic:true,planet:"☊",hardness:7.0,priceMin:2769,priceMax:36923,priceDisplay:"₹2,769 – ₹36,923",unit:"per carat (Ceylon)",desc:"Gomed is the Navaratna gem for Rahu. Its honey-orange to cinnamon glow is distinctive. Ceylon hessonite is prized for its clarity.",specs:{Origin:"Sri Lanka, India, Brazil",Hardness:"7 Mohs",Clarity:"Slightly included",Treatment:"None — naturally untreated","Carat Rate":"₹2,769 – ₹36,923/ct"},benefits:["Rahu planet stone","Career & ambition","Removes obstacles","Mental clarity"],images:[]},
  {id:"fireopal",name:"Fire Opal",hindi:"Agni Opal",scientific:"Hydrated Silica — SiO₂·nH₂O",category:"yellow",badge:"semi",vedic:false,planet:"♀️",hardness:6.0,priceMin:2769,priceMax:276923,priceDisplay:"₹2,769 – ₹2,76,923",unit:"per carat (Mexican)",desc:"Mexican fire opal blazes with orange, red, and gold. Prized for its transparent, saturated body colour. Each stone is completely unique.",specs:{Origin:"Mexico (primary), Brazil",Hardness:"6 Mohs",Clarity:"Translucent–transparent",Treatment:"None (natural)","Carat Rate":"₹2,769 – ₹2,76,923/ct"},benefits:["Passion & creativity","Venus energy","Unique every stone","Collector's gem"],images:[]},
  {id:"diamond",name:"Diamond",hindi:"Heera (हीरा)",scientific:"Carbon — C (cubic)",category:"white",badge:"precious",vedic:true,planet:"♀️",hardness:10.0,priceMin:184615,priceMax:1846154,priceDisplay:"₹1,84,615 – ₹18,46,154",unit:"per carat (D-IF natural)",desc:"The hardest substance on earth. Diamond represents Venus in Vedic astrology, bringing luxury, beauty, and prosperity.",specs:{Origin:"Russia, Botswana, Canada, India",Hardness:"10 Mohs (hardest)",Clarity:"IF to I3 range",Treatment:"Fracture fill (low grade)","Carat Rate":"₹1,84,615 – ₹18,46,154/ct"},benefits:["Venus planet stone","Luxury & beauty","Marriage & love","Eternal investment"],images:[]},
  {id:"whiteopal",name:"White Opal",hindi:"Dugdh Pathar",scientific:"Hydrated Silica — SiO₂·nH₂O",category:"white",badge:"semi",vedic:true,planet:"♀️",hardness:5.5,priceMin:923,priceMax:184615,priceDisplay:"₹923 – ₹1,84,615",unit:"per carat (Lightning Ridge)",desc:"Famous for its mesmerizing play-of-colour — rainbow flashes dancing across a milky white body. No two opals are ever alike.",specs:{Origin:"Australia (Lightning Ridge)",Hardness:"5.5 Mohs",Clarity:"Translucent",Treatment:"Smoke treatment sometimes","Carat Rate":"₹923 – ₹1,84,615/ct"},benefits:["Diamond substitute","Venus energy","Love & creativity","Play-of-colour"],images:[]},
  {id:"amethyst",name:"Amethyst",hindi:"Kathela (कटेला)",scientific:"Quartz — SiO₂",category:"purple",badge:"semi",vedic:true,planet:"♄",hardness:7.0,priceMin:923,priceMax:18462,priceDisplay:"₹923 – ₹18,462",unit:"per carat",desc:"The most beloved purple gemstone. Deep Siberian and Uruguayan amethysts show coveted dark violet hues — a Saturn substitute and powerful healing crystal.",specs:{Origin:"Uruguay, Brazil, Zambia, Russia",Hardness:"7 Mohs",Clarity:"Eye-clean typical",Treatment:"Heat (can produce citrine)","Carat Rate":"₹923 – ₹18,462/ct"},benefits:["Saturn substitute","Calm & peace","Spiritual growth","Anti-stress"],images:[]},
  {id:"pinksapphire",name:"Pink Sapphire",hindi:"Gulabi Pukhraj",scientific:"Corundum — Al₂O₃",category:"purple",badge:"precious",vedic:true,planet:"♀️",hardness:9.0,priceMin:18462,priceMax:739560,priceDisplay:"₹18,462 – ₹7,39,560",unit:"per carat",desc:"Hot pink to soft blush, pink sapphires are second only to rubies in the corundum spectrum. At 9 Mohs ideal for engagement rings.",specs:{Origin:"Sri Lanka, Madagascar, Tanzania",Hardness:"9.0 Mohs",Clarity:"Eye-clean typical",Treatment:"Heat common; unheated prized","Carat Rate":"₹18,462 – ₹7,39,560/ct"},benefits:["Venus planet stone","Love & romance","Marriage stone","Feminine energy"],images:[]},
  {id:"morganite",name:"Morganite",hindi:"Gulabi Beruj",scientific:"Beryl — Be₃Al₂Si₆O₁₈",category:"purple",badge:"semi",vedic:false,planet:"♀️",hardness:7.5,priceMin:4615,priceMax:184615,priceDisplay:"₹4,615 – ₹1,84,615",unit:"per carat",desc:"The rose beryl. Morganite's soft peach-pink to salmon hues have surged in popularity for engagement rings worldwide.",specs:{Origin:"Brazil, Mozambique, Afghanistan",Hardness:"7.5 Mohs",Clarity:"Eye-clean typical",Treatment:"Heat to deepen colour","Carat Rate":"₹4,615 – ₹1,84,615/ct"},benefits:["Love & compassion","Rose gold perfect","Heart chakra","Emotional healing"],images:[]},
  {id:"rhodolite",name:"Rhodolite Garnet",hindi:"Gulabi Garnet",scientific:"Pyrope-Almandine Garnet",category:"purple",badge:"semi",vedic:false,planet:"♀️",hardness:7.0,priceMin:4615,priceMax:138462,priceDisplay:"₹4,615 – ₹1,38,462",unit:"per carat",desc:"A raspberry to grape-purple garnet of exceptional brilliance. Usually untreated and eye-clean.",specs:{Origin:"Tanzania, Zimbabwe, India",Hardness:"7 Mohs",Clarity:"Eye-clean typical",Treatment:"None — naturally untreated","Carat Rate":"₹4,615 – ₹1,38,462/ct"},benefits:["Love & devotion","Venus energy","Untreated natural","Heart chakra"],images:[]}
];

async function seed() {
  try {
    await mongoose.connect(process.env.MONGODB_URI);
    console.log('✅ Connected to MongoDB');
    await Gem.deleteMany({});
    await Admin.deleteMany({});
    await Gem.insertMany(GEMS);
    console.log(`💎 Inserted ${GEMS.length} gems`);
    const admin = new Admin({
      username: process.env.ADMIN_USERNAME || 'hemal_admin',
      password: process.env.ADMIN_PASSWORD || 'Shivratna@2026',
      name: 'Hemal Thakor',
      email: 'hemalthakor2011@gmail.com'
    });
    await admin.save();
    console.log('👤 Admin created — Username:', admin.username);
    console.log('\n✅ Database seeded! Run: npm run dev');
    process.exit(0);
  } catch (err) {
    console.error('❌ Seed error:', err.message);
    process.exit(1);
  }
}
seed();
